### ISSUE TITLE
Terminal Lag Issue

### ISSUE THREAD

**Issue by mobesa** [learn-co-curriculum/irb-readme#14]
**Issue:** Whenever I type in the terminal, at normal typing speed, a few characters get gobbled. There's lag in the console pointer, so I related this to that.
Screenshot of lag aftermath by Learn.co user @wendingp: ![Screenshot](https://s3.amazonaws.com/flatironschool-uploads/a02df243-cdde-4cb7-8303-88619a3c213a.png)

**Comment by mobesa** [comment]
@learn

**Comment by Joll59** [comment]
This looks like an issue with your IDE setup please email support@flatironschool.com or refer to our help center [here](http://help.learn.co/the-learn-ide)
