### ISSUE TITLE
Not seeing the IDE on my screen 

### ISSUE THREAD

**Issue by Hpanora101** [learn-co-curriculum/irb-readme#17]
I'm not seeing the Icon to open up IDE or sandbox on my screen input IRB

**Comment by maxwellbenton** [comment]
Hi @Hpanora101,

Thank you for opening this issue. I've looked into student batches you are a part of and it looks like Sanbox is enabled. I am not able to reproduce the issue you describe, but this lesson's content has been updated and should be in working order now. The instructions also include reference to using Repl.it in the event that Sandbox is not enabled.

We apologize for any confusion this may have caused.
