### ISSUE TITLE
Lesson video unavailable

### ISSUE THREAD

**Issue by Hieuhuule** [learn-co-curriculum/irb-readme#19]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4537/pages/intro-to-irb?module_item_id=262312

## What should be changed?

The video is unavailable

## Additional context

![intro irb video unavailable](https://user-images.githubusercontent.com/24836277/127374801-aaf42728-08f0-4017-ba62-43847332c5ff.jpg)

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up there.

Thanks for contributing to the Flatiron School curriculum! 💙
