### ISSUE TITLE
User unable to open lab -ubuntu

### ISSUE THREAD

**Issue by seemajune** [learn-co-curriculum/irb-readme#8]
Hi, github username farmerbot24 is unable to open this lab. It appears greyed out, even after following the steps here: https://github.com/flatiron-labs/learn-support/blob/master/learn_expert_nitrous_support.md

He says he has been using Windows and switching to ubuntu. Question is open until we have a solution for him: https://learn.co/tracks/intro-to-ruby-development/ruby-basics/debugging/intro-to-irb?batch_id=294&question_uid=q-86f762bd-e25e-452d-9396-a0ec918d3879&track_id=12307

**Comment by AnnJohn** [comment]
Hi @seemajune do you know if this is still an issue for the student? Thanks

**Comment by AnnJohn** [comment]
closing
